export const ActionTypes = {
  //Cart
  GET_CART: 'GET_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  ADJUST_CART: 'ADJUST_CART',
  DROP_CART: 'DROP_CART',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',

  //User
  // SET_FETCHING_STATUS: 'SET_FETCHING_STATUS',
  GET_USER: 'GET_USER',
  DROP_USER: 'DROP_USER',

  //Product
  SET_PRODUCTS: 'SET_PRODUCTS',
};
