export const ActionTypes = {
  //Cart
  FETCH_CART: 'FETCH_CART',
  DROP_CART: 'DROP_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  ADJUST_CART_ITEM: 'ADJUST_CART_ITEM',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',

  //User
  FETCH_USER: 'FETCH_USER',
  DROP_USER: 'DROP_USER',
  UPDATE_USER: 'UPDATE_USER',

  //Product
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',

  //
  FETCH_DETAIL: 'FETCH_DETAIL',
  DROP_DETAIL: 'DROP_DETAIL',
};
